<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo-ii-1c.css" ?>
<!-- ejerciciodtd1c.xml GRUPO 01 -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+, a)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT a (#PCDATA)>
			<!ATTLIST a href CDATA #REQUIRED>
			<!ATTLIST a xmlns CDATA #REQUIRED>
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
 </ficha>
<a href="../../../index.html" xmlns="http://www.w3.org/1999/xhtml">Volver al inicio</a>

</fichero>
