=== mm18226/xmlvalido_GRUPO_01/Parte IV/Ejercicio_4.dtd
<!--Ejercicio_4.dtd-->

<!ELEMENT equipo(Cuerpo_tecnico?, cuerpo_medico, jugadores+)>
<!ELEMENT Cuerpo_tecnico(identificador, tecnico ,tecnico_auxiliar,preparador_fisico)>
<!ELEMENT identificador(#PCDATA)>
<!ELEMENT tecnico(nombre)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT tecnico_auxiliar(nombre)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT preparador_fisico(nombre)>
<!ELEMENT nombre(#PCDATA)>

<!ELEMENT cuerpo_medico(identificador, medicos, socorristas)>
<!ELEMENT identificador(#PCDATA)>
<!ELEMENT medicos(nombre+)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT socorristas(nombre+)>
<!ELEMENT nombre(#PCDATA)>

<!ELEMENT jugadores(identificador,porteros,defensas,mediocampistas,delanteros,a)>
<!ELEMENT identificador(#PCDATA)>
<!ELEMENT porteros(identificador,nombre+)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT defensas(identificador,nombre+)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT mediocampistas(identificador,nombre+)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT delanteros(identificador,nombre+)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT a (#PCDATA)>
		   <!ATTLIST a href CDATA #REQUIRED>
			<!ATTLIST a xmlns CDATA #REQUIRED>

=== mm18226/xmlvalido_GRUPO_01/Parte IV/Ejercicio_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo.css"?>
<!DOCTYPE equipo SYSTEM "Ejercicio_4.dtd">
<equipo>
  <Cuerpo_tecnico id="tecnicos">
   <cartilla>
    <identificador>Cuerpo Tecnico</identificador>
     <tecnico>
       <nombre>Sebastias Aguirre</nombre>
     </tecnico>
     <tecnico_auxiliar>
       <nombre>Pedro Fernandez</nombre>
     </tecnico_auxiliar>
     <preparador_fisico>
       <nombre>Juan Pablo</nombre>
     </preparador_fisico>
      </cartilla>
  </Cuerpo_tecnico>

  <cuerpo_medico>
  <cartilla>
    <Identificador>Cuerpo Medico</Identificador>
    <Medicos id="medicos">
        <nombre>Juan De Dios </nombre>
        <nombre>Fernando  Lopez</nombre>
    </Medicos>
    <socorristas id="socorristas">
      <nombre>Omar Molina</nombre>
      <nombre>Elmer Ramirez</nombre>
      <nombre>Carlos Almarado</nombre>
      <nombre>Armando Arevalo</nombre>
    </socorristas>
    </cartilla>
  </cuerpo_medico>

  <jugadores id="jugadores">
  <cartilla>
     <identificador>Jugadores</identificador>
     <porteros id="P">
       <identificador>Portero</identificador>
       <nombre>Keylor Navas</nombre>
       <nombre>Iker Casillas</nombre>
       <nombre>David de Gea</nombre>
     </porteros>

     <defensas id="D">
        <identificador>Defensas</identificador>
        <nombre>Sergio Ramon</nombre>
        <nombre>Thiago Silva</nombre>
        <nombre>Dani Alves</nombre>
        <nombre>Pedro Beltran</nombre>
         <nombre>Eric Zavaleta</nombre>
        <nombre>Fernando Avelar</nombre>
        <nombre>Jose Fuentes</nombre>
        <nombre>Mario Casas</nombre>
     </defensas>

     <mediocampistas id="M">
        <identificador>Mediocampistas</identificador>
        <nombre>Julio Cesar</nombre>
        <nombre>Juan Mata</nombre>
        <nombre>Felipe Dueñas</nombre>
        <nombre>Adrian Guzman</nombre>
        <nombre>Marcelo Flores</nombre>
        <nombre>Gabriel Muñoz</nombre>
        <nombre>Santiago Dueñas</nombre>
        <nombre>Marlio Aguirre</nombre>
     </mediocampistas>
     <delanteros id="D">
        <identificador>Delanteros</identificador>
        <nombre>Leonel Messi</nombre>
        <nombre>Cristiano Ronaldo</nombre>
        <nombre>Carlos Alfaro</nombre>
     </delanteros>
     </cartilla>
   </jugadores>
<a href="../../index.html" xmlns="http://www.w3.org/1999/xhtml">Volver al inicio</a>
</equipo>
