=== mm18226/xmlvalido_GRUPO_01/Parte II/ejercicios/dtd_externa/fichero-ii2b.dtd
<!-- ficha-ii2b.dtd GRUPO 01-->
<!ELEMENT cuerpo (fichero, a)>
		
			<!ELEMENT fichero (ficha)>
			
		<!ELEMENT ficha (adelante, atras)>
				
		<!ELEMENT adelante (svg)>
			<!ELEMENT svg (texto, path+)>
			<!ELEMENT texto (#PCDATA)>
    <!ATTLIST svg version CDATA  #REQUIRED>
    <!ATTLIST svg id CDATA  #REQUIRED>
    <!ATTLIST svg xmlns CDATA  #REQUIRED>
    <!ATTLIST svg xlink CDATA #REQUIRED >
    <!ATTLIST svg x CDATA #REQUIRED >
    <!ATTLIST svg y CDATA #REQUIRED >
    <!ATTLIST svg viewBox CDATA #REQUIRED>
    <!ATTLIST svg enable-background CDATA  #IMPLIED>
    <!ATTLIST svg height CDATA  #IMPLIED>
    <!ATTLIST svg width CDATA  #IMPLIED>
    <!ATTLIST svg space CDATA  #REQUIRED>
    
            <!ELEMENT path (#PCDATA)>
      <!ATTLIST path fill CDATA  #REQUIRED>
    <!ATTLIST path d CDATA  #REQUIRED>
		
		<!ELEMENT atras (titulo,datos)>
 				<!ELEMENT titulo (#PCDATA | nombre | apellido)*>
		<!ELEMENT nombre (#PCDATA)>	
        <!ELEMENT apellido (#PCDATA)>
		<!ATTLIST apellido edad  CDATA  #IMPLIED>

		 <!ELEMENT datos (sdatos+)> 

<!ELEMENT sdatos (sexo*,direccion*, DUI?)+>
<!ELEMENT sexo (#PCDATA)>	
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>

				<!ELEMENT a (#PCDATA)>
			<!ATTLIST a href CDATA #REQUIRED>
			<!ATTLIST a xmlns CDATA #REQUIRED>

=== mm18226/xmlvalido_GRUPO_01/Parte II/ejercicios/dtd_externa/ejercicio-ii-2b-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo-ii-2b.css" ?>
<!-- ejerciciodtd2b.xml GRUPO 01 -->
<!DOCTYPE fichero SYSTEM "fichero-ii2b.dtd">

<cuerpo>
<fichero>
 <ficha>
 <adelante>
 <svg version="1.1" id="user" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 785.8159 1010" enable-background="new 0 0 785.8159 1010" height="512px" width="512px" space="preserve">
	 <texto></texto>
	<path fill="#323B5A" d="M392.9692,0c135.251,0,244.8565,109.5234,244.8565,244.6914c0,135.312-109.6055,244.8145-244.8565,244.8145
		c-135.1269,0-244.7734-109.5025-244.7734-244.8145C148.1958,109.5234,257.8423,0,392.9692,0z"/>
	<path fill="#323B5A" d="M785.8159,1010h-0.5762H0V876.8457c0-173.7793,109.3999-321.1318,261.9521-376.0586l131.0171,174.6016
		l130.9756-174.6016c152.5938,54.9268,261.8711,202.2793,261.8711,376.0586V1010z"/>
</svg>
 </adelante>
 <atras>
   <titulo>Tarjeta Personal <nombre > Angelina</nombre>
    <apellido edad="17">Fernandez</apellido> 
   </titulo>
 <datos>
  <sdatos>
  <sexo>Femenino</sexo>
	</sdatos>
	<sdatos>
  <direccion>c/Ulises, 36 </direccion>
  </sdatos>
  	<sdatos>
  <DUI>________-_</DUI>
  </sdatos>
  </datos>
 </atras>
 </ficha>
 </fichero>
  <a href="../../../index.html" xmlns="http://www.w3.org/1999/xhtml">Volver al inicio</a>
</cuerpo>
