=== mm18226/xmlvalido_GRUPO_01/Parte III/tareas.dtd
<!--Archivo creado por PC15007-->
<!ELEMENT tareas (grupo+)>
<!ATTLIST tareas procedencia CDATA #FIXED "Universidad de El Salvador">
<!ATTLIST tareas formado (GT | GL | GD) #REQUIRED>
<!ATTLIST tareas num CDATA #REQUIRED>

<!ELEMENT grupo (facultad, carrera, actividad, tema, integrante+)>
<!ATTLIST grupo materia CDATA ID #REQUIRED>
<!ATTLIST grupo encargado CDATA #REQUIRED>
<!ATTLIST grupo numgrupo CDATA #REQUIRED>
<!ATTLIST grupo tema CDATA #REQUIRED>

<!ELEMENT facultad (#PCDATA)>
<!ATTLIST facultad codfac CDATA #REQUIRED>

<!ELEMENT carrera (#PCDATA)>
<!ATTLIST carrera codcarr CDATA #REQUIRED>

<!ELEMENT actividad (#PCDATA)>
<!ATTLIST actividad valor CDATA #REQUIRED>

<!ELEMENT tema (#PCDATA)>

<!ELEMENT integrante (carnet, nombre, apellido, telefono?)>
<!ATTLIST integrante coordinador (si | no) #REQUIRED>
<!ATTLIST integrante sexo (m | f) #REQUIRED>
<!ATTLIST integrante edad CDATA #IMPLIED>

<!ELEMENT carnet (#PCDATA)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT apellido (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>

=== mm18226/xmlvalido_GRUPO_01/Parte III/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="tareas.css" type="text/css"?>
<!DOCTYPE tareas SYSTEM "tareas.dtd">
<!--Archivo creado por PC15007-->
<tareas procedencia="Universidad de El Salvador" formado="GT" num="1">
    <grupo materia="Introduccion" encargado="Dr. Chapatin" numgrupo="1">
        <facultad codfac="MED">Medicina</facultad>
        <carrera codcarr="ODN">Odontologia</carrera>
        <actividad valor="20">Trabajo de investigacion</actividad>
        <tema>Historia de la Odontologia</tema>
        <integrante coordinador="si" sexo="m" edad="12">
            <carnet>EC2021</carnet>
            <nombre>Chavo</nombre>
            <apellido>Del 8</apellido>
            <telefono>1234-5123</telefono>
        </integrante>

        <integrante coordinador="no" sexo="f" edad="40">
            <carnet>FM2021</carnet>
            <nombre>Florinda</nombre>
            <apellido>Mesa</apellido>
            <telefono>2345-6234</telefono>
        </integrante>

        <integrante coordinador="no" sexo="m" edad="45">
            <carnet>PG2021</carnet>
            <nombre>Profesor</nombre>
            <apellido>Girafales</apellido>
            <telefono>3456-7345</telefono>
        </integrante>
        
        <integrante coordinador="no" sexo="m" edad="13">
            <carnet>QM2021</carnet>
            <nombre>Quico</nombre>
            <apellido>Mesa</apellido>
            <telefono>4567-8456</telefono>
        </integrante>
    </grupo>
    <a href="../../index.html" xmlns="http://www.w3.org/1999/xhtml">Volver al inicio</a>
</tareas>
